categories_and_channels:
  type: list
  default: ""
  description:
    en: "List of the secure categories and chat channels to hide the lock badge icon for.  Leave blank to hide for all secured categories. Must be in semi-colon delimited format with category-slug;category-ID. Channel slug name must be same as respective category slug name. Separate parent category and subcategory slugs with a backslash and use subcategory ID. (For example: staff;3 or lounge/vip;8)"

show_lock_icons_for_staff:
  type: bool
  default: true
  description:
    en: "Disable this if you want the lock badge icon to be hidden for staff as well as regular users."

alternative_category_lock_icon:
  default: "lock"
  description:
    en: "If you are using an alternative lock icon, change this to the FontAwesome 6 icon name here"
