categories_and_channels:
  type: list
  list_type: category
  default: ""
  description:
    en: "List of the secure categories and chat channels to hide the lock badge icon for.  Leave blank to hide for all secured categories."

show_lock_icons_for_staff:
  type: bool
  default: true
  description:
    en: "Disable this if you want the lock badge icon to be hidden for staff as well as regular users."
